### PR TITLE
OpaTestRunConfiguration: add the full output of the command to the root node

### LINKED ISSUE #51: Opa test execution: print full command output on root node
# What would you like to be added
When execute `opa test`,  print the executed command and the full output on the root node in the test console.

# Why is this needed
if the command is not correct (invalid option, ...) or the package does not contains any test. No nodes are created and only the only `Testing Framework quit unexpectedly` error message is display to the user

# Implementation details

### PR DESCRIPTION
**Pull request by vgramer**
# Description
Print the executed command and the full output on the root node.

## before
before

## after
after
after-2

 

Fixes #51 

# Special notes for your reviewer

### CODE REVIEW

File: src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestEventsConverter.kt [hunk 1]
```diff
@@ -135,31 +141,40 @@ class OpaTestEventsConverter(
...
-                if (isFailTest(text)) {
+                else if (isFailTest(text)) {
                     // to avoid duplicate fail if we are in the summary section. Error test are only in Summary section
                     if (createCurrentFailedTest(text)) {
                         state = State.FAIL_OUTPUT
                     }
                 }
+                else {
+                    // Add the `text` that is not part of the test result to the root node. (eg L1-4,L21-22 L29-33).
+                    processor.onUncapturedOutput(text, outputType)
```
Comment (asadali) [inline src/main/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestEventsConverter.kt:172]: :+1:

File: src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationBase.kt [hunk 2]
```diff
@@ -43,7 +47,7 @@ abstract class OpaTestRunConfigurationBase : RunConfigurationTestBase() {
             waitFor()
         }
         UIUtil.dispatchAllInvocationEvents()
-        Disposer.dispose(executionConsole)
+        Disposer.register(project,executionConsole)
```
Comment (asadali) [inline src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationBase.kt:50]: IIUC, this will now dispose executionConsole when the root is disposed?

**Review by asadali — APPROVED** [review]

File: src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationBase.kt (hunk 2 above)
Comment (vgramer) [reply src/test/kotlin/org/openpolicyagent/ideaplugin/ide/runconfig/test/OpaTestRunConfigurationBase.kt:50]: `Disposer.dispose(executionConsole)` immediately dispose the executionConsole. The problem is that the output of the root node (printable elements) is also disposed so the output was immediately discarded.

To avoid this we "dispose" the executionConsole when the project is disposed which happens at the end of the Unit test
